### ISSUE TITLE
potential file for LML_W contains file for Fe

### ISSUE THREAD

**Issue by pgrigorev** [ai-atoms/Lammps-MiLaDy#1]
I think the [W_LML.pot](https://github.com/ai-atoms/Lammps-MiLaDy/blob/main/Potentials/W_LML.pot) file actually contains file for Fe. It is identical to [Fe_LML.pot](https://github.com/ai-atoms/Lammps-MiLaDy/blob/main/Potentials/Fe_LML.pot). I guess there was a mistake while creating the files, it would be nice to have it fixed. :sweat_smile:

**Comment by mcmarinica** [comment]
Thank you Piotr. I have change. I hope the right one :). I will close the topic.

**Comment by pgrigorev** [comment]
Hi Cosmin. Thank you very much for the quick response. Just one last thing: the cutoff radius in the updated file is 9.4. Could you please confirm that? it seems a bit large to me.

**Comment by mcmarinica** [comment]
Was fast and bad :)))) Gooooood point Piotr.  Actually was in the former format with 2xRcut. I updated /commited the new form. Just git pull.
Thank you again !!!!

**Comment by pgrigorev** [comment]
You are very welcome. Now it is exactly the same as the one that we used, so everything is consistent which is fantastic :) Thank you very much.
